# Generated by Django 3.1.3 on 2020-12-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='info/')),
                ('description', models.TextField(max_length=200)),
                ('fb_link', models.URLField(max_length=500)),
                ('twitter_link', models.URLField(max_length=500)),
                ('instgram_link', models.URLField(max_length=500)),
                ('address', models.TextField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
