# Generated by Django 3.1.3 on 2020-12-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20201211_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombook',
            name='email',
        ),
    ]
